name: 'mirror'
on:
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '*/5 * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v2
        with:
          origin: 'https://gitee.com/yunws/GWAC_obs_manage_system.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
